# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: # Location of package manifests
      - "/"
      - "/packages/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory:
      - "/packages/functions/layers/dynamo"
      - "/packages/functions/layers/league"
      - "/packages/functions/src/main"
      - "/packages/functions/src/register"
      - "/packages/functions/src/task"
    schedule:
      interval: "weekly"
