# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/configs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    target-branch: "dependencies"
  - package-ecosystem: "pip"
    directory: "/packages/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/packages/functions/src/layers/dynamo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/packages/functions/src/layers/league"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/packages/functions/src/main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/packages/functions/src/register"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/packages/functions/src/task"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
