services:
  db:
    container_name: data
    build: .
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    image: bryxli/zoe-db
  backend:
    container_name: backend
    depends_on:
      - "db"
    links:
      - "db"
    build: ./backend
    ports:
      - "8000:5000"
    image: bryxli/zoe-backend
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - node_modules:/app/node_modules
    image: bryxli/zoe-frontend
volumes:
  mysql-data:
  node_modules: