services:
  db:
    container_name: data
    image: ${DOCKER_REGISTRY}/zoe-bot:db
    build: .
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY}/zoe-bot:backend
    depends_on:
      - "db"
    links:
      - "db"
    build: ./backend
    ports:
      - "8000:5000"
  frontend:
    container_name: frontend
    image: ${DOCKER_REGISTRY}/zoe-bot:frontend
    depends_on:
      - "backend"
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - node_modules:/app/node_modules
volumes:
  mysql-data:
  node_modules: