// TODO: navigation

// Generated by Discord Application under OAuth2 > URL Generator with Scopes: identity
const href =
  "https://discord.com/api/oauth2/authorize?client_id=1154647072138608694&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fuser&response_type=token&scope=identify";

export default function Header() {
  return (
    <>
      <header>zoe, the aspect of twighlight</header>
      <a href={href}>Login with Discord</a>
    </>
  );
}
