// TODO: information
// TODO: generated output
import Header from "./components/Header";

// Generated by Discord Application under OAuth2 > URL Generator with Scopes: identity
const href =
  "https://discord.com/api/oauth2/authorize?client_id=1154647072138608694&redirect_uri=https%3A%2F%2Fbryxli.github.io%2Fzoe-interface%2Fuser&response_type=token&scope=identify";

export default function Home() {
  return (
    <>
      <Header />
      <a href={href}>Login with Discord</a>
      {/** Information */}
      {/** Output */}
    </>
  );
}
