"use client";

import { useContext } from "react";
import { Button, Container } from "react-bootstrap";

import { AuthContext } from "../contexts/AuthContext";
import { useRouter } from "next/navigation";

export default function Header() {
  const router = useRouter();
  const authContext = useContext(AuthContext);
  const { userInfo } = authContext;
  // Generated by Discord Application under OAuth2 > URL Generator with Scopes: identity
  const href =
    "https://discord.com/api/oauth2/authorize?client_id=1154647072138608694&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fload&response_type=token&scope=guilds%20identify";

  const handleLogout = async () => {
    router.push("/");
  };

  return (
    <Container className="d-flex flex-column align-items-center justify-content-center">
      <header>zoe, the aspect of twighlight</header>
      {userInfo ? (
        <Button onClick={handleLogout}>Logout</Button>
      ) : (
        <Button href={href}>Login with Discord</Button>
      )}
    </Container>
  );
}
