name: SST workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  upload-configs:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Create Archive
        run: |
          tar -czf configs.tar.gz -C configs .
      - name: Upload configs
        uses: actions/upload-artifact@v2
        with:
          name: configs
          path: configs.tar.gz
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Download configs
        uses: actions/download-artifact@v2
        with:
          name: configs
      - name: Extract Configs
        run: tar -xzf $GITHUB_WORKSPACE/configs.tar.gz -C $GITHUB_WORKSPACE
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 3600 #adjust as needed for your build time
          aws-region: us-east-1 # TODO: update readme for auto deployment setup
      - name: Deploy app
        run: |
          npm i
          if [ "${{ github.event_name }}" == "push" ]; then
            npx sst deploy --stage prod
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            npx sst deploy --stage dev
          fi
