name: SST workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Debugging Output
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of configs directory: $(ls -R configs)"
      - name: Copy config.json
        run: |
          cp configs/config.json $GITHUB_WORKSPACE/config.json
        shell: bash
      - name: Copy config-dev.json
        run: |
          cp configs/config-dev.json $GITHUB_WORKSPACE/config-dev.json
      - name: Copy config-prod.json
        run: |
          cp configs/config-prod.json $GITHUB_WORKSPACE/config-prod.json
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 3600 #adjust as needed for your build time
          aws-region: us-east-1 # TODO: update readme for auto deployment setup
      - name: Deploy app
        run: |
          npm i
          if [ "${{ github.event_name }}" == "push" ]; then
            npx sst deploy --stage prod
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            npx sst deploy --stage dev
          fi
