name: Dev
on:
  pull_request:
    branches-ignore:
      - "dependencies"

concurrency:
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  unit-tests:
    environment: dev
    runs-on: ubuntu-latest
    env:
      SET_AWS_REGION: ${{secrets.AWS_REGION}}
      RIOT_KEY: ${{secrets.RIOT_KEY}}
      DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
      APPLICATION_ID: ${{secrets.APPLICATION_ID}}
      TOKEN: ${{secrets.TOKEN}}
    defaults:
      run:
        working-directory: ./packages/functions
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r src/main/requirements.txt
          pip install -r src/register/requirements.txt
          pip install -r src/task/requirements.txt
          pip install -r src/layers/dynamo/requirements.txt
          pip install -r src/layers/league/requirements.txt
          pip install coverage
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 60
          aws-region: ${{secrets.AWS_REGION}}
      - name: Run unit tests
        run: |
          coverage run -m unittest
          coverage report --show-missing

  create-config:
    environment: dev
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      RIOT_KEY: ${{secrets.RIOT_KEY}}
      DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
      APPLICATION_ID: ${{secrets.APPLICATION_ID}}
      TOKEN: ${{secrets.TOKEN}}
    steps:
      - name: Create config.json
        run: |
          echo "{ \"aws_region\": \"$AWS_REGION\", \"riot_key\": \"$RIOT_KEY\", \"discord_public_key\": \"$DISCORD_PUBLIC_KEY\", \"application_id\": \"$APPLICATION_ID\", \"token\": \"$TOKEN\" }" > config.json
      - name: Upload config.json
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: config.json

  deploy:
    needs:
      - unit-tests
      - create-config
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Download config.json
        uses: actions/download-artifact@v4
        with:
          name: config
          path: configs
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GitHub
          role-duration-seconds: 600
          aws-region: ${{secrets.AWS_REGION}}
      - name: Deploy dev app
        run: |
          npm i
          npm run deploy
