name: Dev
on: pull_request

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  automated-tests:
    environment: dev
    runs-on: ubuntu-latest
    env:
      SET_AWS_REGION: ${{secrets.AWS_REGION}}
      RIOT_KEY: ${{secrets.RIOT_KEY}}
      DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
      APPLICATION_ID: ${{secrets.APPLICATION_ID}}
      TOKEN: ${{secrets.TOKEN}}
    defaults:
      run:
        working-directory: ./packages/functions
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/ZoeBotApplication
          role-duration-seconds: 900
          aws-region: ${{secrets.AWS_REGION}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install function dependencies
        run: |
          pip install -r src/main/requirements.txt
          pip install -r src/register/requirements.txt
          pip install -r src/task/requirements.txt
          pip install -r src/layers/dynamo/requirements.txt
          pip install -r src/layers/league/requirements.txt
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          coverage run -m unittest
          coverage report --show-missing
      - name: Run acceptance tests
        run: behave

      - name: Install frontend dependencies
        run: npm i
        working-directory: ./packages/frontend
      - name: Run unit tests
        run: npm run test
        working-directory: ./packages/frontend
      - name: Run acceptance tests
        run: echo # TODO: run frontend acceptance test
        working-directory: ./packages/frontend

  create-config:
    environment: dev
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}
      RIOT_KEY: ${{secrets.RIOT_KEY}}
      DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
      APPLICATION_ID: ${{secrets.APPLICATION_ID}}
      TOKEN: ${{secrets.TOKEN}}
    steps:
      - name: Create config.json
        run: |
          echo "{ \"aws_region\": \"$AWS_REGION\", \"riot_key\": \"$RIOT_KEY\", \"discord_public_key\": \"$DISCORD_PUBLIC_KEY\", \"application_id\": \"$APPLICATION_ID\", \"token\": \"$TOKEN\" }" > config.json
      - name: Upload config.json
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: config.json

  deploy:
    concurrency:
      group: deploy
    needs:
      - automated-tests
      - create-config
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Download config.json
        uses: actions/download-artifact@v4
        with:
          name: config
          path: configs
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/ZoeBotActions
          role-duration-seconds: 3600
          aws-region: ${{secrets.AWS_REGION}}
      - name: Deploy dev app
        run: |
          npm i
          npm run deploy

  approve:
    needs: automated-tests
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"

  merge:
    needs: approve
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{secrets.PAT}}
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
